format = """
[ ](bg: inverted fg:#712bc2)\
$hostname\
[ÓÇ∞](bg:#8c6dd3 fg:#712bc2)\
$directory\
[ÓÇ∞](fg:#8c6dd3 bg:#414bd3)\
$git_branch\
$git_status\
[ÓÇ∞](fg:#414bd3 bg:#86BBD8)\
$python\
$rust\
[ÓÇ∞](fg:#86BBD8 bg:#81a1c1)\
$kubernetes\
$docker_context\
[ÓÇ∞](fg:#81a1c1 bg:#5e81ac)\
$character\
$status\
$time\
[ÓÇ∞ ](fg:#5e81ac)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ÔÑ† to save some space
[username]
show_always = true
style_user = "bg:#712bc2 bold"
style_root = "bg:#712bc2 bold"
format = '[$user]($style)'

[hostname]
style = "bg:#712bc2 bold"
format = '[$hostname ]($style)'
ssh_only = false
disabled = false

[directory]
style = "bg:#8c6dd3 bold"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = ""

[docker_context]
symbol = "üê≥ "
style = "bg:#81a1c1 fg:#2e3440 bold"
format = '[ $symbol $context ]($style) $path'

[kubernetes]
symbol = "‚ò∏Ô∏è "
style = "bg:#81a1c1 fg:#2e3440 bold"
format = '[ $symbol $context ]($style)'
disabled = true

[git_branch]
symbol = "ÓÇ†"
style = "bg:#414bd3 bold fg:#f0d58c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#414bd3 bold fg:#ffbe33"
format = '[$all_status$ahead_behind ]($style)'

[python]
symbol = "üêç"
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "Óúò"
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "Óû®"
style = "bg:#88c0d0 fg:#2e3440 bold"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#5e81ac bold"
# format = '[ ‚ô• $time ]($style)'
format = '[$time ]($style)'

[character]
disabled = false
success_symbol = "[](bg:#5e81ac)"
error_symbol = "[ ‚úñ ](bg:#5e81ac)"
# format = '[ ‚ô• $time ]($style)'
format = "$symbol"
