# ~/.config/starship.toml

command_timeout = 10000

[status]
disabled = false

[character]
format = "ğŸª $symbol "
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[container]
disabled = true